# three node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker


# kind create cluster --name k8 --config hack/kind/multi-node-cluster.yaml